version: '3'
services:
  backend:
    build: ./backend
    ports:
      - "8080:8080" # Change if your Go app uses a different port

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development